### ISSUE TITLE
I had the same problems with npm@2, try npm@3.

### ISSUE THREAD

**Issue by aronwoost** [sirreal/broken-react-jsonschema-form#1] opened 2016-09-26 14:23 UTC
👍

**Comment by sirreal** [comment] 2016-09-26 19:00
This was using npm@3. I still have no idea what the problem is/was.

When I run the code in a container, it works initially, although I have had the same problem even within a container.

For background: https://github.com/mozilla-services/react-jsonschema-form/issues/321

You'll see:

```
$ npm ls # (modified for relevant deps)
break-react-jsonschema-form@0.1.0
├── react@15.3.1
├── react-dom@15.3.1
├── react-jsonschema-form@0.40.0
└─┬ react-scripts@0.4.1
  └── webpack@1.13.2 

$ node --version
v6.5.0

$ npm --version
3.10.7
```

Thanks for the suggestion. I'm closing the issue, feel free to re-open or open another with more suggestions.

**Closed by sirreal** 2016-09-26 19:00 UTC
